export interface StockData {
  ticker: string;
  name: string;
  score: number;
  profitability: number;
  growth: number;
  stability: number;
  efficiency: number;
  valuation: number;
  momentum: number;
  trend: number;
  activity: number;
  sentiment: number;
  sector: string;
}

export const stocksData: StockData[] = [
  {
    ticker: "HDFC",
    name: "HDFC Bank",
    score: 85,
    profitability: 88,
    growth: 82,
    stability: 90,
    efficiency: 85,
    valuation: 70,
    momentum: 75,
    trend: 80,
    activity: 85,
    sentiment: 78,
    sector: "Banking",
  },
  {
    ticker: "RELIANCE",
    name: "Reliance Industries",
    score: 83,
    profitability: 85,
    growth: 80,
    stability: 85,
    efficiency: 82,
    valuation: 75,
    momentum: 78,
    trend: 82,
    activity: 80,
    sentiment: 75,
    sector: "Energy",
  },
  {
    ticker: "TCS",
    name: "Tata Consultancy",
    score: 88,
    profitability: 90,
    growth: 85,
    stability: 92,
    efficiency: 88,
    valuation: 73,
    momentum: 82,
    trend: 85,
    activity: 88,
    sentiment: 82,
    sector: "IT",
  },
  {
    ticker: "INFY",
    name: "Infosys",
    score: 86,
    profitability: 88,
    growth: 83,
    stability: 90,
    efficiency: 86,
    valuation: 72,
    momentum: 80,
    trend: 83,
    activity: 86,
    sentiment: 80,
    sector: "IT",
  },
  {
    ticker: "ITC",
    name: "ITC Limited",
    score: 82,
    profitability: 85,
    growth: 75,
    stability: 88,
    efficiency: 80,
    valuation: 78,
    momentum: 72,
    trend: 75,
    activity: 80,
    sentiment: 76,
    sector: "FMCG",
  },
  {
    ticker: "WIPRO",
    name: "Wipro",
    score: 79,
    profitability: 78,
    growth: 75,
    stability: 85,
    efficiency: 80,
    valuation: 77,
    momentum: 74,
    trend: 76,
    activity: 78,
    sentiment: 72,
    sector: "IT",
  },
  {
    ticker: "SBIN",
    name: "State Bank of India",
    score: 78,
    profitability: 72,
    growth: 80,
    stability: 75,
    efficiency: 78,
    valuation: 85,
    momentum: 76,
    trend: 78,
    activity: 82,
    sentiment: 74,
    sector: "Banking",
  },
  {
    ticker: "MARUTI",
    name: "Maruti Suzuki",
    score: 83,
    profitability: 80,
    growth: 85,
    stability: 82,
    efficiency: 84,
    valuation: 74,
    momentum: 82,
    trend: 84,
    activity: 80,
    sentiment: 78,
    sector: "Auto",
  },
  {
    ticker: "TATAMOTORS",
    name: "Tata Motors",
    score: 75,
    profitability: 70,
    growth: 78,
    stability: 72,
    efficiency: 76,
    valuation: 80,
    momentum: 76,
    trend: 78,
    activity: 74,
    sentiment: 70,
    sector: "Auto",
  },
  {
    ticker: "SUNPHARMA",
    name: "Sun Pharmaceutical",
    score: 77,
    profitability: 75,
    growth: 72,
    stability: 80,
    efficiency: 78,
    valuation: 80,
    momentum: 74,
    trend: 76,
    activity: 76,
    sentiment: 72,
    sector: "Pharma",
  },
  {
    ticker: "HCLTECH",
    name: "HCL Technologies",
    score: 84,
    profitability: 85,
    growth: 80,
    stability: 88,
    efficiency: 84,
    valuation: 75,
    momentum: 78,
    trend: 80,
    activity: 84,
    sentiment: 78,
    sector: "IT",
  },
  
  {
    ticker: "BAJFINANCE",
    name: "Bajaj Finance",
    score: 87,
    profitability: 90,
    growth: 88,
    stability: 82,
    efficiency: 87,
    valuation: 68,
    momentum: 85,
    trend: 88,
    activity: 90,
    sentiment: 84,
    sector: "NBFC",
  },
];

export const sectors = [
  "Banking",
  "IT",
  "Auto",
  "Pharma",
  "FMCG",
  "Energy",
  "NBFC",
];
export const assetTypes = [
  "Large Cap",
  "Mid Cap",
  "Small Cap",
  "Blue Chip",
  "Growth",
  "Value",
];
export const biases = [
  "Momentum",
  "Quality",
  "Low Volatility",
  "High Dividend",
  "ESG",
  "Innovation",
];
export const categories = [
  "Technology",
  "Financial Services",
  "Healthcare",
  "Consumer Goods",
  "Energy",
  "Infrastructure",
];

// Portfolio stocks for Health Tab (15 stocks with detailed metrics)
export const portfolioStocks: StockData[] = [
  {
    ticker: "TCS",
    name: "Tata Consultancy Services",
    score: 88,
    profitability: 90,
    growth: 85,
    stability: 92,
    efficiency: 88,
    valuation: 73,
    momentum: 82,
    trend: 85,
    activity: 88,
    sentiment: 82,
    sector: "IT",
  },
  {
    ticker: "HDFC",
    name: "HDFC Bank",
    score: 85,
    profitability: 88,
    growth: 82,
    stability: 90,
    efficiency: 85,
    valuation: 70,
    momentum: 75,
    trend: 80,
    activity: 85,
    sentiment: 78,
    sector: "Banking",
  },
  {
    ticker: "RELIANCE",
    name: "Reliance Industries",
    score: 83,
    profitability: 85,
    growth: 80,
    stability: 85,
    efficiency: 82,
    valuation: 75,
    momentum: 78,
    trend: 82,
    activity: 80,
    sentiment: 75,
    sector: "Energy",
  },
  {
    ticker: "INFY",
    name: "Infosys",
    score: 86,
    profitability: 88,
    growth: 83,
    stability: 90,
    efficiency: 86,
    valuation: 72,
    momentum: 80,
    trend: 83,
    activity: 86,
    sentiment: 80,
    sector: "IT",
  },
  {
    ticker: "ITC",
    name: "ITC Limited",
    score: 82,
    profitability: 85,
    growth: 75,
    stability: 88,
    efficiency: 80,
    valuation: 78,
    momentum: 72,
    trend: 75,
    activity: 80,
    sentiment: 76,
    sector: "FMCG",
  },
  {
    ticker: "BAJFINANCE",
    name: "Bajaj Finance",
    score: 87,
    profitability: 90,
    growth: 88,
    stability: 82,
    efficiency: 87,
    valuation: 68,
    momentum: 85,
    trend: 88,
    activity: 90,
    sentiment: 84,
    sector: "NBFC",
  },
  {
    ticker: "HCLTECH",
    name: "HCL Technologies",
    score: 84,
    profitability: 85,
    growth: 80,
    stability: 88,
    efficiency: 84,
    valuation: 75,
    momentum: 78,
    trend: 80,
    activity: 84,
    sentiment: 78,
    sector: "IT",
  },
  {
    ticker: "MARUTI",
    name: "Maruti Suzuki",
    score: 83,
    profitability: 80,
    growth: 85,
    stability: 82,
    efficiency: 84,
    valuation: 74,
    momentum: 82,
    trend: 84,
    activity: 80,
    sentiment: 78,
    sector: "Auto",
  },
  {
    ticker: "WIPRO",
    name: "Wipro",
    score: 79,
    profitability: 78,
    growth: 75,
    stability: 85,
    efficiency: 80,
    valuation: 77,
    momentum: 74,
    trend: 76,
    activity: 78,
    sentiment: 72,
    sector: "IT",
  },
  {
    ticker: "SBIN",
    name: "State Bank of India",
    score: 78,
    profitability: 72,
    growth: 80,
    stability: 75,
    efficiency: 78,
    valuation: 85,
    momentum: 76,
    trend: 78,
    activity: 82,
    sentiment: 74,
    sector: "Banking",
  },
  {
    ticker: "ASIANPAINT",
    name: "Asian Paints",
    score: 81,
    profitability: 84,
    growth: 78,
    stability: 86,
    efficiency: 82,
    valuation: 71,
    momentum: 77,
    trend: 79,
    activity: 81,
    sentiment: 75,
    sector: "FMCG",
  },
  {
    ticker: "SUNPHARMA",
    name: "Sun Pharmaceutical",
    score: 77,
    profitability: 75,
    growth: 72,
    stability: 80,
    efficiency: 78,
    valuation: 80,
    momentum: 74,
    trend: 76,
    activity: 76,
    sentiment: 72,
    sector: "Pharma",
  },
  {
    ticker: "TATAMOTORS",
    name: "Tata Motors",
    score: 75,
    profitability: 70,
    growth: 78,
    stability: 72,
    efficiency: 76,
    valuation: 80,
    momentum: 76,
    trend: 78,
    activity: 74,
    sentiment: 70,
    sector: "Auto",
  },
  {
    ticker: "TATASTEEL",
    name: "Tata Steel",
    score: 73,
    profitability: 68,
    growth: 74,
    stability: 70,
    efficiency: 75,
    valuation: 82,
    momentum: 72,
    trend: 74,
    activity: 73,
    sentiment: 68,
    sector: "Metals",
  },
  {
    ticker: "ADANIPORTS",
    name: "Adani Ports",
    score: 76,
    profitability: 74,
    growth: 79,
    stability: 76,
    efficiency: 77,
    valuation: 73,
    momentum: 75,
    trend: 77,
    activity: 76,
    sentiment: 71,
    sector: "Infrastructure",
  },
];
